name: ai_hr
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  sentry_flutter: ^9.3.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  socket_io_client: ^3.1.2
  logging: ^1.3.0
  meta: ^1.16.0
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  bloc_concurrency: ^0.3.0
  firebase_messaging: ^15.2.9
  firebase_core: ^3.15.1
  flutter_local_notifications: ^19.3.0
  shared_preferences: ^2.5.3
  unique_identifier: ^0.4.0
  mqtt_client: ^10.8.0
  typed_data: ^1.4.0
  translit: ^2.0.2
  flutter_secure_storage: ^9.2.4
  drift: ^2.28.0
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5

dev_dependencies:
  sentry_dart_plugin: ^3.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.28.1-dev.0
  build_runner: ^2.6.0-dev.1

flutter:
  uses-material-design: true

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: flutter
  org: k-teleco
